logging:
  level:
    de:
      sba: info
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:E:\\dev\\database\\h2\\discordbot\\h2
de:
  sba:
    discordbot:
      nic-names:
        - Best Bot EU
        - Topix Bot Extended
      topic:
        auto-topic-targets:
          Der Kult: [general, experimente-mit-best-bot-eu]
          sba: [general]